## SQL at Scale with Spark SQL

Welcome to the SQL mini project. For this project, you will use the Databricks Platform and work through a series of exercises using Spark SQL. The dataset size may not be too big but the intent here is to familiarize yourself with the Spark SQL interface which scales easily to huge datasets, without you having to worry about changing your SQL queries. 

The data you need is present in the mini-project folder in the form of three CSV files. This data will be imported in Databricks to create the following tables under the __`country_club`__ database.

<br>
1. The __`bookings`__ table,
2. The __`facilities`__ table, and
3. The __`members`__ table.

You will be uploading these datasets shortly into the Databricks platform to understand how to create a database within minutes! Once the database and the tables are populated, you will be focusing on the mini-project questions.

In the mini project, you'll be asked a series of questions. You can solve them using the databricks platform, but for the final deliverable,
please download this notebook as an IPython notebook (__`File -> Export -> IPython Notebook`__) and upload it to your GitHub.

### Creating the Database

We will first create our database in which we will be creating our three tables of interest

In [0]:
%sql 
drop database if exists country_club cascade;
create database country_club;
show databases;

databaseName
country_club
default

### Creating the Tables

In this section, we will be creating the three tables of interest and populate them with the data from the CSV files already available to you. 
To get started, first upload the three CSV files to the DBFS as depicted in the following figure

![](https://i.imgur.com/QcCruBr.png)


Once you have done this, please remember to execute the following code to build the dataframes which will be saved as tables in our database

In [0]:
# File location and type
file_location_bookings = "/FileStore/tables/Bookings.csv"
file_location_facilities = "/FileStore/tables/Facilities.csv"
file_location_members = "/FileStore/tables/Members.csv"

file_type = "csv"

# CSV options
infer_schema = "true"
first_row_is_header = "true"
delimiter = ","

# The applied options are for CSV files. For other file types, these will be ignored.
bookings_df = (spark.read.format(file_type) 
                    .option("inferSchema", infer_schema) 
                    .option("header", first_row_is_header) 
                    .option("sep", delimiter) 
                    .load(file_location_bookings))

facilities_df = (spark.read.format(file_type) 
                      .option("inferSchema", infer_schema) 
                      .option("header", first_row_is_header) 
                      .option("sep", delimiter) 
                      .load(file_location_facilities))

members_df = (spark.read.format(file_type) 
                      .option("inferSchema", infer_schema) 
                      .option("header", first_row_is_header) 
                      .option("sep", delimiter) 
                      .load(file_location_members))

### Viewing the dataframe schemas

We can take a look at the schemas of our potential tables to be written to our database soon

In [0]:
print('Bookings Schema')
bookings_df.printSchema()
print('Facilities Schema')
facilities_df.printSchema()
print('Members Schema')
members_df.printSchema()

### Create permanent tables
We will be creating three permanent tables here in our __`country_club`__ database as we discussed previously with the following code

In [0]:
permanent_table_name_bookings = "country_club.Bookings"
bookings_df.write.format("parquet").saveAsTable(permanent_table_name_bookings)

permanent_table_name_facilities = "country_club.Facilities"
facilities_df.write.format("parquet").saveAsTable(permanent_table_name_facilities)

permanent_table_name_members = "country_club.Members"
members_df.write.format("parquet").saveAsTable(permanent_table_name_members)

### Refresh tables and check them

In [0]:
%sql
use country_club;
REFRESH table bookings;
REFRESH table facilities;
REFRESH table members;
show tables;

database,tableName,isTemporary
country_club,bookings,false
country_club,facilities,false
country_club,members,false

### Test a sample SQL query

__Note:__ You can use __`%sql`__ at the beginning of a cell and write SQL queries directly as seen in the following cell. Neat isn't it!

In [0]:
%sql
select * from bookings limit 3

bookid,facid,memid,starttime,slots
0,3,1,2012-07-03 11:00:00,2
1,4,1,2012-07-03 08:00:00,2
2,6,0,2012-07-03 18:00:00,2

#### Q1: Some of the facilities charge a fee to members, but some do not. Please list the names of the facilities that do.

In [0]:
%sql
select name 
from facilities 
where membercost > 0.0

name
Tennis Court 1
Tennis Court 2
Massage Room 1
Massage Room 2
Squash Court

####  Q2: How many facilities do not charge a fee to members?

In [0]:
%sql
select count(distinct facid) as free_facilities 
from facilities 
where membercost == 0.0

free_facilities
4

#### Q3: How can you produce a list of facilities that charge a fee to members, where the fee is less than 20% of the facility's monthly maintenance cost? 
#### Return the facid, facility name, member cost, and monthly maintenance of the facilities in question.

In [0]:
%sql
select 
    facid, 
    name, 
    membercost, 
    monthlymaintenance 
from facilities 
where 
    (membercost < (monthlymaintenance * .2)) 
    and (membercost > 0)

facid,name,membercost,monthlymaintenance
0,Tennis Court 1,5.0,200
1,Tennis Court 2,5.0,200
4,Massage Room 1,9.9,3000
5,Massage Room 2,9.9,3000
6,Squash Court,3.5,80

#### Q4: How can you retrieve the details of facilities with ID 1 and 5? Write the query without using the OR operator.

In [0]:
%sql
select * 
from facilities 
where facid 
      in (1,5)

facid,name,membercost,guestcost,initialoutlay,monthlymaintenance
1,Tennis Court 2,5.0,25.0,8000,200
5,Massage Room 2,9.9,80.0,4000,3000

#### Q5: How can you produce a list of facilities, with each labelled as 'cheap' or 'expensive', depending on if their monthly maintenance cost is more than $100? 
#### Return the name and monthly maintenance of the facilities in question.

In [0]:
%sql
select 
    name, 
    monthlymaintenance, 
    if (monthlymaintenance > 100, 'expensive', 'cheap') as type 
from facilities

name,monthlymaintenance,type
Tennis Court 1,200,expensive
Tennis Court 2,200,expensive
Badminton Court,50,cheap
Table Tennis,10,cheap
Massage Room 1,3000,expensive
Massage Room 2,3000,expensive
Squash Court,80,cheap
Snooker Table,15,cheap
Pool Table,15,cheap

#### Q6: You'd like to get the first and last name of the last member(s) who signed up. Do not use the LIMIT clause for your solution.

In [0]:
%sql
select 
    firstname, 
    surname 
from 
    members 
where 
    (firstname != 'GUEST') or (surname != 'GUEST') 
group by 
    firstname, 
    surname

firstname,surname
Timothy,Baker
David,Farrell
Burton,Tracy
Tim,Boothe
Erica,Crumpet
Tracy,Smith
Gerald,Butters
Charles,Owen
Hyacinth,Tupperware
David,Pinker
Anne,Baker
Douglas,Jones
Anna,Mackenzie
Ponder,Stibbons
Millicent,Purview
Henry,Worthington-Smyth
Nancy,Dare
David,Jones
Tim,Rownam
Janice,Joplette
Florence,Bader
Jemima,Farrell
Ramnaresh,Sarwin
Henrietta,Rumney
Darren,Smith
Matthew,Genting
John,Hunt
Joan,Coplin
Jack,Smith

####  Q7: How can you produce a list of all members who have used a tennis court?
- Include in your output the name of the court, and the name of the member formatted as a single column. 
- Ensure no duplicate data
- Also order by the member name.

In [0]:
%sql
select 
    concat(members.firstname," ",members.surname) as member_name, facilities.name
from 
    bookings
inner join facilities 
    on facilities.facid = bookings.facid
inner join members 
    on members.memid = bookings.memid
where 
    (
      (members.firstname != 'GUEST') or (members.surname != 'GUEST')
    ) and (facilities.name LIKE '%Tennis Court%') 
group by 
    member_name, 
    facilities.name
order by 
    member_name,
    facilities.name

member_name,name
Anne Baker,Tennis Court 1
Anne Baker,Tennis Court 2
Burton Tracy,Tennis Court 1
Burton Tracy,Tennis Court 2
Charles Owen,Tennis Court 1
Charles Owen,Tennis Court 2
Darren Smith,Tennis Court 2
David Farrell,Tennis Court 1
David Farrell,Tennis Court 2
David Jones,Tennis Court 1
David Jones,Tennis Court 2
David Pinker,Tennis Court 1
Douglas Jones,Tennis Court 1
Erica Crumpet,Tennis Court 1
Florence Bader,Tennis Court 1
Florence Bader,Tennis Court 2
Gerald Butters,Tennis Court 1
Gerald Butters,Tennis Court 2
Henrietta Rumney,Tennis Court 2
Jack Smith,Tennis Court 1
Jack Smith,Tennis Court 2
Janice Joplette,Tennis Court 1
Janice Joplette,Tennis Court 2
Jemima Farrell,Tennis Court 1
Jemima Farrell,Tennis Court 2
Joan Coplin,Tennis Court 1
John Hunt,Tennis Court 1
John Hunt,Tennis Court 2
Matthew Genting,Tennis Court 1
Millicent Purview,Tennis Court 2
Nancy Dare,Tennis Court 1
Nancy Dare,Tennis Court 2
Ponder Stibbons,Tennis Court 1
Ponder Stibbons,Tennis Court 2
Ramnaresh Sarwin,Tennis Court 1
Ramnaresh Sarwin,Tennis Court 2
Tim Boothe,Tennis Court 1
Tim Boothe,Tennis Court 2
Tim Rownam,Tennis Court 1
Tim Rownam,Tennis Court 2
Timothy Baker,Tennis Court 1
Timothy Baker,Tennis Court 2
Tracy Smith,Tennis Court 1
Tracy Smith,Tennis Court 2

#### Q8: How can you produce a list of bookings on the day of 2012-09-14 which will cost the member (or guest) more than $30? 

- Remember that guests have different costs to members (the listed costs are per half-hour 'slot')
- The guest user's ID is always 0. 

#### Include in your output the name of the facility, the name of the member formatted as a single column, and the cost.

- Order by descending cost, and do not use any subqueries.

In [0]:
%sql
select 
      facilities.name as facility_name,
       concat(members.firstname," ",members.surname) as member_name,
       if (bookings.memid = 0, bookings.slots * facilities.membercost, bookings.slots * facilities.guestcost) as the_cost,
       bookings.starttime as date
from 
      bookings
inner join facilities 
      on facilities.facid = bookings.facid
inner join members 
      on members.memid = bookings.memid
where 
      (if (bookings.memid = 0, bookings.slots * facilities.membercost, bookings.slots * facilities.guestcost)) > 30
      and (cast(starttime as date)='2012-09-14') 
order by 
    the_cost desc

facility_name,member_name,the_cost,date
Massage Room 1,Jemima Farrell,320.0,2012-09-14 14:00:00
Massage Room 1,Jemima Farrell,160.0,2012-09-14 11:00:00
Massage Room 2,Florence Bader,160.0,2012-09-14 09:30:00
Massage Room 1,Jack Smith,160.0,2012-09-14 08:00:00
Massage Room 1,Ponder Stibbons,160.0,2012-09-14 12:00:00
Massage Room 1,Burton Tracy,160.0,2012-09-14 18:00:00
Massage Room 1,Matthew Genting,160.0,2012-09-14 19:00:00
Tennis Court 2,David Jones,150.0,2012-09-14 08:00:00
Tennis Court 2,Tim Boothe,150.0,2012-09-14 11:00:00
Tennis Court 1,Burton Tracy,75.0,2012-09-14 08:00:00
Tennis Court 1,Gerald Butters,75.0,2012-09-14 12:30:00
Tennis Court 1,David Pinker,75.0,2012-09-14 10:00:00
Tennis Court 1,Tim Rownam,75.0,2012-09-14 14:00:00
Tennis Court 1,Douglas Jones,75.0,2012-09-14 17:30:00
Badminton Court,Darren Smith,46.5,2012-09-14 13:00:00
Badminton Court,Gerald Butters,46.5,2012-09-14 16:00:00
Badminton Court,Anna Mackenzie,46.5,2012-09-14 11:00:00
Badminton Court,Ponder Stibbons,46.5,2012-09-14 18:00:00
Badminton Court,Darren Smith,46.5,2012-09-14 08:00:00
Massage Room 2,GUEST GUEST,39.6,2012-09-14 11:00:00
Squash Court,Anne Baker,35.0,2012-09-14 08:30:00
Squash Court,Timothy Baker,35.0,2012-09-14 14:00:00
Squash Court,David Pinker,35.0,2012-09-14 17:30:00
Squash Court,Anne Baker,35.0,2012-09-14 16:00:00

#### Q9: This time, produce the same result as in Q8, but using a subquery.

In [0]:
%sql    
select 
    facilities.name as facility_name,
    concat(members.firstname," ",members.surname) as member_name,
    the_cost,
    date
from 
    (
        select 
            bookings.memid as b_memid,
            bookings.facid as b_facid,
            facilities.facid as f_facid,
            if (bookings.memid = 0, bookings.slots * facilities.membercost, bookings.slots * facilities.guestcost) as the_cost,
            bookings.starttime as date
        from bookings
        inner join facilities 
            on facilities.facid = bookings.facid
        where 
            cast(starttime as date)='2012-09-14' 
            and (if (bookings.memid = 0, bookings.slots * facilities.membercost, bookings.slots * facilities.guestcost)) > 30
     )
inner join members 
      on members.memid = b_memid
inner join facilities 
      on facilities.facid = f_facid
      
order by 
      the_cost desc;

facility_name,member_name,the_cost,date
Massage Room 1,Jemima Farrell,320.0,2012-09-14 14:00:00
Massage Room 1,Jemima Farrell,160.0,2012-09-14 11:00:00
Massage Room 2,Florence Bader,160.0,2012-09-14 09:30:00
Massage Room 1,Jack Smith,160.0,2012-09-14 08:00:00
Massage Room 1,Ponder Stibbons,160.0,2012-09-14 12:00:00
Massage Room 1,Burton Tracy,160.0,2012-09-14 18:00:00
Massage Room 1,Matthew Genting,160.0,2012-09-14 19:00:00
Tennis Court 2,David Jones,150.0,2012-09-14 08:00:00
Tennis Court 2,Tim Boothe,150.0,2012-09-14 11:00:00
Tennis Court 1,Burton Tracy,75.0,2012-09-14 08:00:00
Tennis Court 1,Gerald Butters,75.0,2012-09-14 12:30:00
Tennis Court 1,David Pinker,75.0,2012-09-14 10:00:00
Tennis Court 1,Tim Rownam,75.0,2012-09-14 14:00:00
Tennis Court 1,Douglas Jones,75.0,2012-09-14 17:30:00
Badminton Court,Darren Smith,46.5,2012-09-14 13:00:00
Badminton Court,Gerald Butters,46.5,2012-09-14 16:00:00
Badminton Court,Anna Mackenzie,46.5,2012-09-14 11:00:00
Badminton Court,Ponder Stibbons,46.5,2012-09-14 18:00:00
Badminton Court,Darren Smith,46.5,2012-09-14 08:00:00
Massage Room 2,GUEST GUEST,39.6,2012-09-14 11:00:00
Squash Court,Anne Baker,35.0,2012-09-14 08:30:00
Squash Court,Timothy Baker,35.0,2012-09-14 14:00:00
Squash Court,David Pinker,35.0,2012-09-14 17:30:00
Squash Court,Anne Baker,35.0,2012-09-14 16:00:00

#### Q10: Produce a list of facilities with a total revenue less than 1000.
- The output should have facility name and total revenue, sorted by revenue. 
- Remember that there's a different cost for guests and members!

In [0]:
%sql    
select 
    facility_name,
    total_revenue
from (
    select
      facilities.name as facility_name,
      sum (
              case when 
                  bookings.memid = 0 
              then 
                  bookings.slots * facilities.guestcost
              else
                  bookings.slots * facilities.membercost
              end
           ) as total_revenue
    from facilities
    inner join bookings 
          on facilities.facid = bookings.facid   
    group by facilities.name
 )
where total_revenue < 1000
order by 
    total_revenue

facility_name,total_revenue
Table Tennis,180.0
Snooker Table,240.0
Pool Table,270.0